---
name: Workflow - Pull Request

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  spell_check:
    name: Spell check
    uses: ./.github/workflows/spell_check.yml

  rust-tests:
    name: Rust tests
    uses: ./.github/workflows/rust_test.yml

  deno-tests:
    name: Deno tests
    uses: ./.github/workflows/deno_test.yml

  trunk-check:
    name: Trunk check
    permissions:
      checks: write
      contents: read
    uses: ./.github/workflows/trunk_check.yml
